name: Deployflow
on: 
  push:
    branches:
    - main

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Cloning code
          uses: actions/checkout@v7.0.0
        - name: echo
          run: echo "Hello"
        - name: List code space 
          run: ls
    
