name: Deployflow
on: 
  push:
    branches:
    - main
permissions:
  id-token: write 
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Cloning code
          uses: actions/checkout@v7.0.0
        - name: echo
          run: echo "Hello"
        - name: List code space 
          run: ls
        - name: "Configure AWS Credentials" 
          uses: aws-actions/configure-aws-credentials@v6.2.2
          with:
            audience: sts.amazonaws.com
            aws-region: ap-south-1
            role-to-assume: arn:aws:iam::794038225665:role/github-actions
        - name: list s3
          run: aws s3 list
